In [ ]:
!pip install torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 --index-url https://download.pytorch.org/whl/cu126

In [18]:
import torch
import numpy
print(torch.cuda.is_available())

True


# 张量及定义

In [19]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
print(x.shape)
print(x.numel)

torch.Size([12])
<built-in method numel of Tensor object at 0x7b7bafa90b90>


要想改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数。 例如，可以把张量x从形状为（12,）的行向量转换为形状为（3,4）的矩阵。

In [21]:
X = x.reshape(3,4)
print(X)
print(X.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


在知道宽度后，高度会被自动计算得出，不必我们自己做除法。可以通过-1来调用此自动计算出维度的功能。 即我们可以用x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)。

In [22]:
X = x.reshape(-1,4)
print(X)
print(X.shape)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])


使用全0、全1、其他常量创建初始化矩阵

In [23]:
print(f"创建全0的初始化矩阵\n{torch.zeros((2,3,4))}")
print(f"创建全1的初始化矩阵\n{torch.ones((2,3,4))}")
print(f"通过python列表创建初始化矩阵\n{torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])}")


创建全0的初始化矩阵
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
创建全1的初始化矩阵
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
通过python列表创建初始化矩阵
tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])


# 运算符

按元素（elementwise）运算。 它们将标准标量运算符应用于数组的每个元素。

In [24]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
# x + y, x - y, x * y, x / y, x ** y
print(f"x + y = {x+y}")
print(f"x - y = {x-y}")
print(f"x * y = {x*y}")
print(f"x / y = {x/y}")
print(f"x ** y = {x**y}")
#exp
print(f"exp(x) = {torch.exp(x)}")

x + y = tensor([ 3.,  4.,  6., 10.])
x - y = tensor([-1.,  0.,  2.,  6.])
x * y = tensor([ 2.,  4.,  8., 16.])
x / y = tensor([0.5000, 1.0000, 2.0000, 4.0000])
x ** y = tensor([ 1.,  4., 16., 64.])
exp(x) = tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])


把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量。

In [25]:
X = torch.arange(12,dtype=torch.float32).reshape((3,4))
print(X)
Y =torch.tensor([
    [2.,1,4,3],
    [1,2,3,4],
    [4,3,2,1]
])
print(Y)

print(f"dim=0,按行连结\n{torch.cat((X,Y),dim=0)}")
print(f"dim=1,按列连结\n{torch.cat((X,Y),dim=1)}")


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
dim=0,按行连结
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]])
dim=1,按列连结
tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [26]:
print(f"通过运算符构建二元张量\n {X==Y}")

print(f"求和\n {X.sum()}")

通过运算符构建二元张量
 tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])
求和
 66.0


## 广播机制
在 Python 的数值计算库 NumPy 中，以及在深度学习库 PyTorch 中，广播 (Broadcasting) 是一种强大的机制，它允许对形状不完全相同的数组（或 tensors）进行算术运算。广播机制的核心思想是在运算过程中，NumPy 或 PyTorch 会自动“扩展”维度较小的数组，使其形状与维度较大的数组兼容，从而能够进行逐元素的操作。

In [27]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

由于a和b分别是 3x1 和 1x2 矩阵，如果让它们相加，它们的形状不匹配。 我们将两个矩阵广播为一个更大的 3x2 矩阵，如下所示：矩阵a将复制列， 矩阵b将复制行，然后再按元素相加。

In [28]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 索引和切片

切片是左闭右开区间: 在Python和PyTorch中，使用 [start:stop] 进行切片时，表示从 start 位置开始，到 stop 位置之前结束，不包含 stop 位置的元素。

In [30]:
print(X)
X[-1], X[1:3]

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [31]:
print(f"写入前\n {X}")
X[1,2] = 9
X

写入前tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [32]:
X[0:2, :] = 12 # [0:2, :]访问第1行和第2行，其中“:”代表沿轴1（列）的所有元素。
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])